version: '3'

services:
  sneakers:
    build: .
    depends_on:
      - rabbitmq
      - redis
    volumes:
     - .:/sneakers
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
